packages:
  - "apps/*"
  - "packages/*"
  - "packages/sources/*"
  - "packages/destinations/*"
exclude:
  - "packages/sources"
  - "packages/destinations"

onlyBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
  - sharp
  - msgpackr-extract
